name: backoffice-ci

run-name: ${{ github.actor }}

on: [push]
jobs:

  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: changeme
          
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: cd ../quizer/backoffice/scripts && bash run_ubuntu_comands.sh
      - run: |
        VERSION_STRING="107.0.3"
        wget "https://dl.google.com/linux/direct/google-chrome-stable_${VERSION_STRING}_amd64.deb"
        sudo dpkg -i "google-chrome-stable_${VERSION_STRING}_amd64.deb"
      - run: cd ../quizer/backoffice/scripts && bash run_bg.sh
