name: backoffice-ci

run-name: ${{ github.actor }}

on: [push]
jobs:

  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - run: cd ../quizer/backoffice/scripts && bash run_ubuntu_comands.sh
    - run: cd ../quizer/backoffice/scripts && bash run_bg.sh
  
