name: backoffice-ci

run-name: ${{ github.actor }}

on: [push]
jobs:

  build:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: Install and start PostgreSQL
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql postgresql-client
        sudo -u postgres psql -c "SELECT datname, datdba, datpath FROM pg_catalog.pg_database;"
        sudo -u postgres pg_ctlcluster 12 main start
    - name: Run SQL script
      run: |
        psql -U postgres -f sql/script.sql
    - run: cd ../quizer/backoffice/scripts && bash run_ubuntu_comands.sh
    - run: cd ../quizer/backoffice/scripts && bash run_bg.sh
  
